<a href="https://colab.research.google.com/github/InduYadav689/Diabetes_Prediction/blob/main/Diabetes_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score



In [ ]:
dataset = pd.read_csv('diabetes.csv')
dataset



Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0              6      148             72  ...                     0.627   50        1
1              1       85             66  ...                     0.351   31        0
2              8      183             64  ...                     0.672   32        1
3              1       89             66  ...                     0.167   21        0
4              0      137             40  ...                     2.288   33        1
..           ...      ...            ...  ...                       ...  ...      ...
763           10      101             76  ...                     0.171   63        0
764            2      122             70  ...                     0.340   27        0
765            5      121             72  ...                     0.245   30        0
766            1      126             60  ...                     0.349   47        1
767            1       93             70  ...                     0.315   23        0

[768 rows x 9 columns]

In [ ]:
dataset.head()




Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
dataset.shape

(768, 9)

In [ ]:
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

Differenciating the data into independent  and dependent variables


In [ ]:
dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  ...        BMI  DiabetesPedigreeFunction        Age
Outcome                                          ...                                                
0           3.298000  109.980000      68.184000  ...  30.304200                  0.429734  31.190000
1           4.865672  141.257463      70.824627  ...  35.142537                  0.550500  37.067164

[2 rows x 8 columns]

In [ ]:
x = dataset[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]
x

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [ ]:
y = dataset[['Outcome']]
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

Transforming data into Arrays


In [ ]:
x = dataset[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
y = dataset[['Outcome']].values
y

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [ ]:
dataset[['Outcome']].value_counts()

Outcome
0          500
1          268
Name: count, dtype: int64

Standardizing the data






In [ ]:
scaler = StandardScaler().fit(x_train)
print(scaler)

StandardScaler()


In [ ]:
scaler.fit(x)

StandardScaler()

In [ ]:
scaler.fit(x)
scaler.transform(x)
standardized_data = scaler.transform(x)
standardized_data


array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
x = standardized_data


In [ ]:
y = dataset['Outcome']
print(x)
print(y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


Train Test Split

In [ ]:
x_train,x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, stratify=y, random_state=2)
print(x.shape, x_train.shape, x_test.shape)

(768, 8) (614, 8) (154, 8)


Training the model

In [ ]:
scaler = StandardScaler().fit(x_train)
print(scaler)
scaler.transform(x_train)
standardized_data = scaler.transform(x_train)
standardized_data

StandardScaler()


array([[-1.13796489, -0.07971099, -3.5556072 , ...,  0.02825037,
        -0.98159708, -0.7885233 ],
       [ 0.64067858, -0.52091877,  0.02549599, ..., -0.17184452,
        -1.03823795,  0.31879426],
       [-0.84152431,  2.12632792, -0.48609018, ..., -0.25938604,
        -0.21545477,  2.19271628],
       ...,
       [ 2.12288146, -1.15121561,  0.23013046, ..., -0.25938604,
        -0.50760242,  0.14843771],
       [ 0.04779742, -0.30031488,  0.43476492, ...,  0.90366551,
        -0.69839272,  0.40397253],
       [-1.13796489, -1.11970076, -0.07682125, ...,  0.45345201,
        -0.69243053, -0.70334503]])

In [ ]:
classifier = svm.SVC(kernel='linear')
classifier.fit(x_train, y_train)

Model Evaluation

Accuracy Score

In [ ]:
#Accuracy score on the training data
x_train_prediction = classifier.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)
print('Accuracy Score of the training data:',training_data_accuracy )

Accuracy Score of the training data: 0.7866449511400652


In [ ]:
#Accuracy score on the testing data
x_test_prediction = classifier.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction, y_test)
print('Accuracy Score of the testing data:',testing_data_accuracy )

Accuracy Score of the testing data: 0.7727272727272727


Making Predictive System

In [ ]:

input_data = (6,148,72,35,0,33.6,0.627,50)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)


[[ 5.99123942e+00  1.49009451e+02  7.12288768e+01  3.47103642e+01
  -2.82944389e-02  3.30849071e+01  6.23676874e-01  5.00517920e+01]]
[1]
